### ISSUE TITLE
Editing routes - adding intermediate route points

### ISSUE THREAD

**Issue by tasker25** [sfreytag/simonlikesmaps#42]
You used to be able to create an additional route point in the middle of a route by dragging the solid circle that appeared between existing route points in editing mode. This facility seems to have disappeared and you can now only add route points at the end of the route. The previous functionality was very useful.

M Burnell

**Comment by tasker25** [comment]
Seems to be working again now.

**Comment by sfreytag** [comment]
Hi Martin, thanks for adding this and glad you are still using SLM. Sorry for slow response, was away skiing. Nothing should have changed in this area so I am not quite sure why it stopped working for you but good that it started again.

**Comment by sfreytag** [comment]
@tasker25 I have started some discussions to help me plan a fairly major rewrite of SLM as a new version, the reasoning is explained here: https://github.com/sfreytag/simonlikesmaps/discussions/43

It would be great to get your input for anything you might want to see added to the app or likewise if you think it should stay as it is - any thoughts appreciated.

**Comment by sfreytag** [comment]
I've turned off the discussion - any general comments can now be added to #50
