### ISSUE TITLE
Cancelling Save route deletes route

### ISSUE THREAD

**Issue by rowenahamilton** [sfreytag/simonlikesmaps#47]
You've made a route, you go to save it then realise that you haven;t finished yet, then when you cancel the save action, it deletes the live route you were working on!

**Comment by sfreytag** [comment]
Thanks for this bug report, this will get fixed as part of the ongoing upgrade to SLM2 - see https://github.com/sfreytag/simonlikesmaps/discussions/43

If you have any general ideas about improving SLM please contribute to the discussions!

**Comment by sfreytag** [comment]
Discussions now closed - use #50 for any general discussion.

**Comment by sfreytag** [comment]
This is now fixed in SLM2 which is available to be tried at https://new.simonlikesmaps.com
