### ISSUE TITLE
Suspected bug - route visible indicator

### ISSUE THREAD

**Issue by tasker25** [sfreytag/simonlikesmaps#55]
In the drop down list of existing plans there is a toggle indicating whether each route is visible. I think this toggle should  just be an indicator and not capable of being activated by clicking, but in fact you can click the toggle to turn it on and the route title is then displayed on the map but **not** the actual route. If you have tried to turned visibility on by clicking the toggle and then click 'View' on the list of routes, you get an error message. When you have turned visibility on with the toggle but the route is not displayed, you have to click 'Edit route' followed by 'Cancel' to make the route appear. Just a small bug and only affects people stupid enough to click the indicator in the first place!

Very happy with the new version and am now using it exclusively.

**Comment by sfreytag** [comment]
Thanks, well spotted. I could be persuaded either way as to what this toggle should do. However on the old SimonLikesMaps the visibility column has a 'yes|no' toggle that does correctly show and hide the route, so I have fixed this to do the same... as you say, people might not realise they can click it, but if they do, then it can be a useful way to show a few plans in one go. Thanks for the positive comment! 11 users so far have made the switch.
